#pragma config(Sensor, in4,    linefollower1,  sensorLineFollower)
#pragma config(Sensor, in6,    linefollower3,  sensorLineFollower)
#pragma config(Sensor, in7,    linefollower2,  sensorLineFollower)
#pragma config(Sensor, dgtl1,  bumpswitch,     sensorTouch)
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           motor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motor3,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           motor4,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           servo1,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           servo2,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){

		if((SensorValue(linefollower2)>2400) && (SensorValue(linefollower1)>2400) && (SensorValue(linefollower3)>2400)){

			stopMotor(port2);
			stopMotor(port3);
			wait(4);
			setServo(port5,120);
			setServo(port6,-120);
			wait(2);
			startMotor(port2,30);
			startMotor(port3,30);
			wait1Msec(10);

		}
		else if(SensorValue(linefollower2) > 2400){

			startMotor(port2,-30);
			startMotor(port3,30);

		}
		else if(SensorValue(linefollower3)>2400){

			startMotor(port2, 30);
			startMotor(port3, -30);

		}
		else if(SensorValue(linefollower1)>2400){

			startMotor(port2,30);
			startMotor(port3,30);

		}
	}
}
