#pragma config(Sensor, in1,    linefollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightsensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitswitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpswitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title:
Team Members:
Date:
Section:


Task Description:


Pseudocode:

*/

task main()
{
		while (true)
		if(untilLight(400,linefollower1)){//if first line follower detects line then turn left
		startMotor(port3,90);//robot should go slow in order to give time to correct error
		wait(1);
		startMotor(port4,90);
		wait(1);//needed a long time to set the motors to run    																time would need to be calibrated
		startMotor(port1,45);
		wait(1);
		startMotor(port2,45);
		wait(1);
		//turns by supplying more power to the right drive train then the left drive train
	}
	else if(untilLight(400,linefollower2)//if second line follower detects line then go strait
	{
		startMotor(port1,60);//run all motors at the same speed
		wait(1);
		startMotor(port2,60);
		wait(1);
		startMotor(port3,60);
		wait(1);
		startMotor(port4,60);
		wait(1);
	}
	else	if(untilLight(400,linefollower3)){//if third line follower detects line then turn right
		startMotor(port2,90);
		wait(1);
		startMotor(port1,90);
		wait(1);
		startMotor(port3,45);
		wait(1);
		startMotor(port4,45);



}
